-- Updated create_tags_table.sql

-- Drop the table if it already exists
DROP TABLE IF EXISTS tags;

-- Create the tags table with FAISS ID integration
CREATE TABLE IF NOT EXISTS tags (
    tag TEXT PRIMARY KEY COLLATE NOCASE,
    embedding BLOB NOT NULL,
    faiss_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Note: The faiss_id column is used to store the ID generated by FAISS for each tag.
-- This integration supports efficient vector similarity searches by leveraging FAISS's capabilities.

-- Add any necessary changes or additions here


-- Add a new index on the 'tag' column for faster search performance
CREATE INDEX IF NOT EXISTS idx_tags_tag ON tags (tag);

CREATE INDEX IF NOT EXISTS idx_tags_faiss_id ON tags (faiss_id);

-- Add a trigger to automatically update the 'created_at' column on insert
CREATE TRIGGER IF NOT EXISTS trg_tags_created_at
AFTER INSERT ON tags
BEGIN
    UPDATE tags SET created_at = CURRENT_TIMESTAMP WHERE rowid = NEW.rowid;
END;

-- Add a trigger to automatically update the 'created_at' column on update
CREATE TRIGGER IF NOT EXISTS trg_tags_updated_at
AFTER UPDATE ON tags
BEGIN
    UPDATE tags SET created_at = CURRENT_TIMESTAMP WHERE rowid = NEW.rowid;
END;


--
